// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaXcV8deBzH7iOuZ7fCzmjLcdE-L9MQGY',
    appId: '1:774386778209:web:aacfb4994ced7f1d902a20',
    messagingSenderId: '774386778209',
    projectId: 'cryptocoin-app-b4a67',
    authDomain: 'cryptocoin-app-b4a67.firebaseapp.com',
    storageBucket: 'cryptocoin-app-b4a67.appspot.com',
    measurementId: 'G-KNVCWPH7DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9gmTxYEXLpaas9Hrsj_hoPl-2o_WqiYs',
    appId: '1:774386778209:android:b44718154fb147d6902a20',
    messagingSenderId: '774386778209',
    projectId: 'cryptocoin-app-b4a67',
    storageBucket: 'cryptocoin-app-b4a67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdr86KnQmoN95z7tIbrhyqXpBol8O3t5k',
    appId: '1:774386778209:ios:333d35b69a407f86902a20',
    messagingSenderId: '774386778209',
    projectId: 'cryptocoin-app-b4a67',
    storageBucket: 'cryptocoin-app-b4a67.appspot.com',
    iosBundleId: 'com.example.cryptocoinList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdr86KnQmoN95z7tIbrhyqXpBol8O3t5k',
    appId: '1:774386778209:ios:333d35b69a407f86902a20',
    messagingSenderId: '774386778209',
    projectId: 'cryptocoin-app-b4a67',
    storageBucket: 'cryptocoin-app-b4a67.appspot.com',
    iosBundleId: 'com.example.cryptocoinList',
  );
}
